add image viewbox clipping
linebender/velato pull request #16
Opened 2024-04-05 02:26 UTC by luke1188

2024-04-05 12:48 UTC, simbleau requested changes
It was probably a mistake to include "frame_for_time" so let's remove that, then we can merge this.

2024-04-05 12:48 UTC, simbleau commented on src/runtime/mod.rs
> +    }
```suggestion
```

This didn't have anything to do with viewbox clipping

2024-04-06 18:31 UTC, simbleau approved these changes
Looks good.

2024-04-06 19:28 UTC, DJMcNab commented
I've re-run the CI, as the failure looked spurious

@simbleau, how do you want this PR to be merged? I'd suggest that you just press the green button yourself

2024-04-06 19:54 UTC, simbleau commented
I'll merge it tomorrow, when i have time to add to the changelog and release a patch version (0.1.1)

I consider the lack of viewbox clipping to be a bug, since many Lotties depend on it.

2024-04-29 23:38 UTC, merged