Disable default features on `vello` to remove `wgpu`
linebender/velato pull request #17
Opened 2024-04-29 09:00 UTC by MarijnS95

https://github.com/linebender/vello/pull/359 made `wgpu` an optional but default dependency/feature, but any crate using `velato` will be forced to opt in to `wgpu` due to not disabling the default here.

---

Note that `with_winit` runs briefly (with `wgpu`), but if I don't manage to immediately fullscreen it, it panics:

```
thread 'main' panicked at examples/with_winit/src/lib.rs:436:30:
failed to get surface texture: Timeout
```

This is on a Wayland compositor with AMD GPU. I'm not a WGPU expert and don't dare to immediately say where it is being used wrong.

2024-04-29 09:34 UTC, MarijnS95 commented
Looks like the same fix needs to be applied to [`vello_svg`](https://github.com/linebender/vello_svg/blob/main/Cargo.toml).

2024-04-29 22:38 UTC, simbleau commented
Can you explain why we wouldn't want the default feature for `wgpu`?

2024-04-29 22:41 UTC, MarijnS95 commented
So that crates using `vello` with their own rendering backend - without `wgpu` - can use the Lottie loader/render implementation provided here, without pulling that dependency in? Same reasoning as https://github.com/linebender/vello/pull/359 that did it for the `vello` crate.

2024-04-29 23:39 UTC, simbleau commented
Please update the CHANGELOG and I can merge this

2024-04-30 11:58 UTC, MarijnS95 commented
Before pushing an updated changelog: since this crate reexports `vello` from the root, does it make sense to forward the `wgpu` feature by adding `wgpu = ["vello/wgpu"]`?

2024-04-30 12:19 UTC, simbleau commented
Yeah, let's do that.

2024-05-03 09:28 UTC, MarijnS95 commented
@simbleau done.

2024-05-03 14:43 UTC, simbleau requested changes
Let's change that feature name to just `wgpu`.

2024-05-03 14:43 UTC, simbleau commented on CHANGELOG.md
> +- Disable `vello`'s default `wgpu` feature, and provide a `vello-wgpu` feature to turn it back on. ([#17](https://github.com/linebender/velato/pull/17))
```suggestion
- Disable `vello`'s default `wgpu` feature, and provide a `wgpu` feature to turn it back on. ([#17](https://github.com/linebender/velato/pull/17))
```

2024-05-03 14:43 UTC, simbleau commented on Cargo.toml
> +vello-wgpu = ["vello/wgpu"]
```suggestion
wgpu = ["vello/wgpu"]
```

2024-05-05 16:24 UTC, simbleau approved these changes
Thanks!

2024-05-05 16:28 UTC, merged